// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/proto/presence.proto

package presencepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PresenceRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserPhone     string                 `protobuf:"bytes,1,opt,name=user_phone,json=userPhone,proto3" json:"user_phone,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceRecord) Reset() {
	*x = PresenceRecord{}
	mi := &file_pkg_proto_presence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceRecord) ProtoMessage() {}

func (x *PresenceRecord) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_presence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceRecord.ProtoReflect.Descriptor instead.
func (*PresenceRecord) Descriptor() ([]byte, []int) {
	return file_pkg_proto_presence_proto_rawDescGZIP(), []int{0}
}

func (x *PresenceRecord) GetUserPhone() string {
	if x != nil {
		return x.UserPhone
	}
	return ""
}

func (x *PresenceRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PresenceRecord) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

type GetPresenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserPhone     string                 `protobuf:"bytes,1,opt,name=user_phone,json=userPhone,proto3" json:"user_phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresenceRequest) Reset() {
	*x = GetPresenceRequest{}
	mi := &file_pkg_proto_presence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresenceRequest) ProtoMessage() {}

func (x *GetPresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_presence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresenceRequest.ProtoReflect.Descriptor instead.
func (*GetPresenceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_presence_proto_rawDescGZIP(), []int{1}
}

func (x *GetPresenceRequest) GetUserPhone() string {
	if x != nil {
		return x.UserPhone
	}
	return ""
}

type GetPresenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Presence      *PresenceRecord        `protobuf:"bytes,1,opt,name=presence,proto3" json:"presence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresenceResponse) Reset() {
	*x = GetPresenceResponse{}
	mi := &file_pkg_proto_presence_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresenceResponse) ProtoMessage() {}

func (x *GetPresenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_presence_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresenceResponse.ProtoReflect.Descriptor instead.
func (*GetPresenceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_presence_proto_rawDescGZIP(), []int{2}
}

func (x *GetPresenceResponse) GetPresence() *PresenceRecord {
	if x != nil {
		return x.Presence
	}
	return nil
}

type GetBulkPresenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserPhones    []string               `protobuf:"bytes,1,rep,name=user_phones,json=userPhones,proto3" json:"user_phones,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBulkPresenceRequest) Reset() {
	*x = GetBulkPresenceRequest{}
	mi := &file_pkg_proto_presence_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBulkPresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBulkPresenceRequest) ProtoMessage() {}

func (x *GetBulkPresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_presence_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBulkPresenceRequest.ProtoReflect.Descriptor instead.
func (*GetBulkPresenceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_presence_proto_rawDescGZIP(), []int{3}
}

func (x *GetBulkPresenceRequest) GetUserPhones() []string {
	if x != nil {
		return x.UserPhones
	}
	return nil
}

type GetBulkPresenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*PresenceRecord      `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBulkPresenceResponse) Reset() {
	*x = GetBulkPresenceResponse{}
	mi := &file_pkg_proto_presence_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBulkPresenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBulkPresenceResponse) ProtoMessage() {}

func (x *GetBulkPresenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_presence_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBulkPresenceResponse.ProtoReflect.Descriptor instead.
func (*GetBulkPresenceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_presence_proto_rawDescGZIP(), []int{4}
}

func (x *GetBulkPresenceResponse) GetRecords() []*PresenceRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_pkg_proto_presence_proto protoreflect.FileDescriptor

const file_pkg_proto_presence_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/proto/presence.proto\x12\bpresence\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x01\n" +
	"\x0ePresenceRecord\x12\x1d\n" +
	"\n" +
	"user_phone\x18\x01 \x01(\tR\tuserPhone\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x127\n" +
	"\tlast_seen\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\"3\n" +
	"\x12GetPresenceRequest\x12\x1d\n" +
	"\n" +
	"user_phone\x18\x01 \x01(\tR\tuserPhone\"K\n" +
	"\x13GetPresenceResponse\x124\n" +
	"\bpresence\x18\x01 \x01(\v2\x18.presence.PresenceRecordR\bpresence\"9\n" +
	"\x16GetBulkPresenceRequest\x12\x1f\n" +
	"\vuser_phones\x18\x01 \x03(\tR\n" +
	"userPhones\"M\n" +
	"\x17GetBulkPresenceResponse\x122\n" +
	"\arecords\x18\x01 \x03(\v2\x18.presence.PresenceRecordR\arecords2\xb5\x01\n" +
	"\x0fPresenceService\x12J\n" +
	"\vGetPresence\x12\x1c.presence.GetPresenceRequest\x1a\x1d.presence.GetPresenceResponse\x12V\n" +
	"\x0fGetBulkPresence\x12 .presence.GetBulkPresenceRequest\x1a!.presence.GetBulkPresenceResponseB\"Z wire-server/pkg/proto/presencepbb\x06proto3"

var (
	file_pkg_proto_presence_proto_rawDescOnce sync.Once
	file_pkg_proto_presence_proto_rawDescData []byte
)

func file_pkg_proto_presence_proto_rawDescGZIP() []byte {
	file_pkg_proto_presence_proto_rawDescOnce.Do(func() {
		file_pkg_proto_presence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_presence_proto_rawDesc), len(file_pkg_proto_presence_proto_rawDesc)))
	})
	return file_pkg_proto_presence_proto_rawDescData
}

var file_pkg_proto_presence_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_proto_presence_proto_goTypes = []any{
	(*PresenceRecord)(nil),          // 0: presence.PresenceRecord
	(*GetPresenceRequest)(nil),      // 1: presence.GetPresenceRequest
	(*GetPresenceResponse)(nil),     // 2: presence.GetPresenceResponse
	(*GetBulkPresenceRequest)(nil),  // 3: presence.GetBulkPresenceRequest
	(*GetBulkPresenceResponse)(nil), // 4: presence.GetBulkPresenceResponse
	(*timestamppb.Timestamp)(nil),   // 5: google.protobuf.Timestamp
}
var file_pkg_proto_presence_proto_depIdxs = []int32{
	5, // 0: presence.PresenceRecord.last_seen:type_name -> google.protobuf.Timestamp
	0, // 1: presence.GetPresenceResponse.presence:type_name -> presence.PresenceRecord
	0, // 2: presence.GetBulkPresenceResponse.records:type_name -> presence.PresenceRecord
	1, // 3: presence.PresenceService.GetPresence:input_type -> presence.GetPresenceRequest
	3, // 4: presence.PresenceService.GetBulkPresence:input_type -> presence.GetBulkPresenceRequest
	2, // 5: presence.PresenceService.GetPresence:output_type -> presence.GetPresenceResponse
	4, // 6: presence.PresenceService.GetBulkPresence:output_type -> presence.GetBulkPresenceResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_proto_presence_proto_init() }
func file_pkg_proto_presence_proto_init() {
	if File_pkg_proto_presence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_presence_proto_rawDesc), len(file_pkg_proto_presence_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_presence_proto_goTypes,
		DependencyIndexes: file_pkg_proto_presence_proto_depIdxs,
		MessageInfos:      file_pkg_proto_presence_proto_msgTypes,
	}.Build()
	File_pkg_proto_presence_proto = out.File
	file_pkg_proto_presence_proto_goTypes = nil
	file_pkg_proto_presence_proto_depIdxs = nil
}
