// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_service.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGroupMembers = `-- name: GetGroupMembers :many
SELECT user_phone
FROM group_members
WHERE group_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetGroupMembers(ctx context.Context, groupID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_phone string
		if err := rows.Scan(&user_phone); err != nil {
			return nil, err
		}
		items = append(items, user_phone)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT
    id,
    conversation_id,
    sender_phone,
    body,
    media_url,
    created_at,
    recipient_phone,
    group_id,
    body_encrypted,
    body_type,
    server_ts
FROM messages
WHERE id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, id string) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderPhone,
		&i.Body,
		&i.MediaUrl,
		&i.CreatedAt,
		&i.RecipientPhone,
		&i.GroupID,
		&i.BodyEncrypted,
		&i.BodyType,
		&i.ServerTs,
	)
	return i, err
}

const getMessageHistory = `-- name: GetMessageHistory :many
SELECT
    m.id,
    m.conversation_id,
    m.sender_phone,
    m.body,
    m.media_url,
    m.created_at,
    m.recipient_phone,
    m.group_id,
    m.body_encrypted,
    m.body_type,
    m.server_ts
FROM messages m
LEFT JOIN messages cursor_msg ON cursor_msg.id = $2
WHERE m.conversation_id = $1
  AND ($2::text = '' OR m.created_at < cursor_msg.created_at)
ORDER BY m.created_at DESC, m.id DESC
LIMIT $3
`

type GetMessageHistoryParams struct {
	ConversationID string
	ID             string
	Limit          int32
}

func (q *Queries) GetMessageHistory(ctx context.Context, arg GetMessageHistoryParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessageHistory, arg.ConversationID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderPhone,
			&i.Body,
			&i.MediaUrl,
			&i.CreatedAt,
			&i.RecipientPhone,
			&i.GroupID,
			&i.BodyEncrypted,
			&i.BodyType,
			&i.ServerTs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (
    sender_phone,
    recipient_phone,
    group_id,
    body_encrypted,
    body_type,
    server_ts,
    body,
    conversation_id,
    created_at
)
VALUES (
    $1, $2, $3, $4, $5, NOW(), $6, $7, NOW()
)
RETURNING
    id,
    conversation_id,
    sender_phone,
    body,
    media_url,
    created_at,
    recipient_phone,
    group_id,
    body_encrypted,
    body_type,
    server_ts
`

type InsertMessageParams struct {
	SenderPhone    string
	RecipientPhone pgtype.Text
	GroupID        pgtype.Text
	BodyEncrypted  string
	BodyType       string
	Body           string
	ConversationID string
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.SenderPhone,
		arg.RecipientPhone,
		arg.GroupID,
		arg.BodyEncrypted,
		arg.BodyType,
		arg.Body,
		arg.ConversationID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderPhone,
		&i.Body,
		&i.MediaUrl,
		&i.CreatedAt,
		&i.RecipientPhone,
		&i.GroupID,
		&i.BodyEncrypted,
		&i.BodyType,
		&i.ServerTs,
	)
	return i, err
}

const upsertMessageStatus = `-- name: UpsertMessageStatus :exec
INSERT INTO message_status (message_id, user_phone, status, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (message_id, user_phone)
DO UPDATE SET status = EXCLUDED.status, updated_at = NOW()
`

type UpsertMessageStatusParams struct {
	MessageID string
	UserPhone string
	Status    string
}

func (q *Queries) UpsertMessageStatus(ctx context.Context, arg UpsertMessageStatusParams) error {
	_, err := q.db.Exec(ctx, upsertMessageStatus, arg.MessageID, arg.UserPhone, arg.Status)
	return err
}
