// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addConversationMember = `-- name: AddConversationMember :one
INSERT INTO conversation_members (conversation_id, user_phone, created_at)
VALUES ($1, $2, NOW())
ON CONFLICT (conversation_id, user_phone) DO UPDATE SET created_at = conversation_members.created_at
RETURNING conversation_id, user_phone, created_at
`

type AddConversationMemberParams struct {
	ConversationID string
	UserPhone      string
}

func (q *Queries) AddConversationMember(ctx context.Context, arg AddConversationMemberParams) (ConversationMember, error) {
	row := q.db.QueryRow(ctx, addConversationMember, arg.ConversationID, arg.UserPhone)
	var i ConversationMember
	err := row.Scan(&i.ConversationID, &i.UserPhone, &i.CreatedAt)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (id, conversation_id, sender_phone, body, media_url, created_at)
VALUES ($1, $2, $3, $4, $5, NOW())
RETURNING id, conversation_id, sender_phone, body, media_url, created_at
`

type CreateMessageParams struct {
	ID             string
	ConversationID string
	SenderPhone    string
	Body           string
	MediaUrl       pgtype.Text
}

type CreateMessageRow struct {
	ID             string
	ConversationID string
	SenderPhone    string
	Body           string
	MediaUrl       pgtype.Text
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (CreateMessageRow, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.ConversationID,
		arg.SenderPhone,
		arg.Body,
		arg.MediaUrl,
	)
	var i CreateMessageRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderPhone,
		&i.Body,
		&i.MediaUrl,
		&i.CreatedAt,
	)
	return i, err
}

const ensureConversation = `-- name: EnsureConversation :exec
INSERT INTO conversations (id, kind, created_at)
VALUES ($1, $2, NOW())
ON CONFLICT (id) DO NOTHING
`

type EnsureConversationParams struct {
	ID   string
	Kind string
}

func (q *Queries) EnsureConversation(ctx context.Context, arg EnsureConversationParams) error {
	_, err := q.db.Exec(ctx, ensureConversation, arg.ID, arg.Kind)
	return err
}

const findUsersByPhones = `-- name: FindUsersByPhones :many
SELECT phone
FROM users
WHERE phone = ANY($1::text[])
`

func (q *Queries) FindUsersByPhones(ctx context.Context, dollar_1 []string) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, findUsersByPhones, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var phone pgtype.Text
		if err := rows.Scan(&phone); err != nil {
			return nil, err
		}
		items = append(items, phone)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMediaObject = `-- name: InsertMediaObject :one
INSERT INTO media_objects (id, owner_phone, bucket, object_key, content_type, size_bytes, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
RETURNING id, owner_phone, bucket, object_key, content_type, size_bytes, status, created_at
`

type InsertMediaObjectParams struct {
	ID          string
	OwnerPhone  string
	Bucket      string
	ObjectKey   string
	ContentType string
	SizeBytes   int64
	Status      string
}

func (q *Queries) InsertMediaObject(ctx context.Context, arg InsertMediaObjectParams) (MediaObject, error) {
	row := q.db.QueryRow(ctx, insertMediaObject,
		arg.ID,
		arg.OwnerPhone,
		arg.Bucket,
		arg.ObjectKey,
		arg.ContentType,
		arg.SizeBytes,
		arg.Status,
	)
	var i MediaObject
	err := row.Scan(
		&i.ID,
		&i.OwnerPhone,
		&i.Bucket,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listConversationMembers = `-- name: ListConversationMembers :many
SELECT conversation_id, user_phone, created_at
FROM conversation_members
WHERE conversation_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListConversationMembers(ctx context.Context, conversationID string) ([]ConversationMember, error) {
	rows, err := q.db.Query(ctx, listConversationMembers, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConversationMember
	for rows.Next() {
		var i ConversationMember
		if err := rows.Scan(&i.ConversationID, &i.UserPhone, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPresence = `-- name: UpdateUserPresence :exec
INSERT INTO user_presence (user_phone, status, last_seen, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (user_phone)
DO UPDATE SET status = EXCLUDED.status, last_seen = EXCLUDED.last_seen, updated_at = NOW()
`

type UpdateUserPresenceParams struct {
	UserPhone string
	Status    string
	LastSeen  pgtype.Timestamptz
}

func (q *Queries) UpdateUserPresence(ctx context.Context, arg UpdateUserPresenceParams) error {
	_, err := q.db.Exec(ctx, updateUserPresence, arg.UserPhone, arg.Status, arg.LastSeen)
	return err
}

const upsertReceipt = `-- name: UpsertReceipt :one
INSERT INTO message_receipts (message_id, user_phone, status, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (message_id, user_phone)
DO UPDATE SET status = EXCLUDED.status, updated_at = NOW()
RETURNING message_id, user_phone, status, updated_at
`

type UpsertReceiptParams struct {
	MessageID string
	UserPhone string
	Status    string
}

func (q *Queries) UpsertReceipt(ctx context.Context, arg UpsertReceiptParams) (MessageReceipt, error) {
	row := q.db.QueryRow(ctx, upsertReceipt, arg.MessageID, arg.UserPhone, arg.Status)
	var i MessageReceipt
	err := row.Scan(
		&i.MessageID,
		&i.UserPhone,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}
