// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Conversation struct {
	ID        string
	Kind      string
	CreatedAt pgtype.Timestamptz
}

type ConversationMember struct {
	ConversationID string
	UserPhone      string
	CreatedAt      pgtype.Timestamptz
}

type Group struct {
	ID             string
	Name           string
	Description    pgtype.Text
	AvatarUrl      pgtype.Text
	CreatedByPhone string
	InviteCode     string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type GroupMember struct {
	GroupID   string
	UserPhone string
	CreatedAt pgtype.Timestamptz
	Role      string
	AddedBy   pgtype.Text
}

type MediaObject struct {
	ID          string
	OwnerPhone  string
	Bucket      string
	ObjectKey   string
	ContentType string
	SizeBytes   int64
	Status      string
	CreatedAt   pgtype.Timestamptz
}

type Message struct {
	ID             string
	ConversationID string
	SenderPhone    string
	Body           string
	MediaUrl       pgtype.Text
	CreatedAt      pgtype.Timestamptz
	RecipientPhone pgtype.Text
	GroupID        pgtype.Text
	BodyEncrypted  string
	BodyType       string
	ServerTs       pgtype.Timestamptz
}

type MessageReceipt struct {
	MessageID string
	UserPhone string
	Status    string
	UpdatedAt pgtype.Timestamptz
}

type MessageStatus struct {
	MessageID string
	UserPhone string
	Status    string
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID        string
	Email     string
	Role      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Phone     pgtype.Text
}

type UserPresence struct {
	UserPhone string
	Status    string
	LastSeen  pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
