// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/proto/media.proto

package mediapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestUploadURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerPhone    string                 `protobuf:"bytes,1,opt,name=owner_phone,json=ownerPhone,proto3" json:"owner_phone,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestUploadURLRequest) Reset() {
	*x = RequestUploadURLRequest{}
	mi := &file_pkg_proto_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestUploadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUploadURLRequest) ProtoMessage() {}

func (x *RequestUploadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUploadURLRequest.ProtoReflect.Descriptor instead.
func (*RequestUploadURLRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_media_proto_rawDescGZIP(), []int{0}
}

func (x *RequestUploadURLRequest) GetOwnerPhone() string {
	if x != nil {
		return x.OwnerPhone
	}
	return ""
}

func (x *RequestUploadURLRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *RequestUploadURLRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type RequestUploadURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestUploadURLResponse) Reset() {
	*x = RequestUploadURLResponse{}
	mi := &file_pkg_proto_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestUploadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUploadURLResponse) ProtoMessage() {}

func (x *RequestUploadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUploadURLResponse.ProtoReflect.Descriptor instead.
func (*RequestUploadURLResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_media_proto_rawDescGZIP(), []int{1}
}

func (x *RequestUploadURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RequestUploadURLResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *RequestUploadURLResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type GetMediaItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaItemRequest) Reset() {
	*x = GetMediaItemRequest{}
	mi := &file_pkg_proto_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaItemRequest) ProtoMessage() {}

func (x *GetMediaItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaItemRequest.ProtoReflect.Descriptor instead.
func (*GetMediaItemRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_media_proto_rawDescGZIP(), []int{2}
}

func (x *GetMediaItemRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

type MediaItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	OwnerPhone    string                 `protobuf:"bytes,2,opt,name=owner_phone,json=ownerPhone,proto3" json:"owner_phone,omitempty"`
	Bucket        string                 `protobuf:"bytes,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,4,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaItem) Reset() {
	*x = MediaItem{}
	mi := &file_pkg_proto_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaItem) ProtoMessage() {}

func (x *MediaItem) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaItem.ProtoReflect.Descriptor instead.
func (*MediaItem) Descriptor() ([]byte, []int) {
	return file_pkg_proto_media_proto_rawDescGZIP(), []int{3}
}

func (x *MediaItem) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *MediaItem) GetOwnerPhone() string {
	if x != nil {
		return x.OwnerPhone
	}
	return ""
}

func (x *MediaItem) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *MediaItem) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *MediaItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MediaItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetMediaItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *MediaItem             `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaItemResponse) Reset() {
	*x = GetMediaItemResponse{}
	mi := &file_pkg_proto_media_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaItemResponse) ProtoMessage() {}

func (x *GetMediaItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_media_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaItemResponse.ProtoReflect.Descriptor instead.
func (*GetMediaItemResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_media_proto_rawDescGZIP(), []int{4}
}

func (x *GetMediaItemResponse) GetItem() *MediaItem {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_pkg_proto_media_proto protoreflect.FileDescriptor

const file_pkg_proto_media_proto_rawDesc = "" +
	"\n" +
	"\x15pkg/proto/media.proto\x12\x05media\x1a\x1fgoogle/protobuf/timestamp.proto\"q\n" +
	"\x17RequestUploadURLRequest\x12\x1f\n" +
	"\vowner_phone\x18\x01 \x01(\tR\n" +
	"ownerPhone\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"\xeb\x01\n" +
	"\x18RequestUploadURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12F\n" +
	"\aheaders\x18\x02 \x03(\v2,.media.RequestUploadURLResponse.HeadersEntryR\aheaders\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"0\n" +
	"\x13GetMediaItemRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\"\xd1\x01\n" +
	"\tMediaItem\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x1f\n" +
	"\vowner_phone\x18\x02 \x01(\tR\n" +
	"ownerPhone\x12\x16\n" +
	"\x06bucket\x18\x03 \x01(\tR\x06bucket\x12\x1d\n" +
	"\n" +
	"object_key\x18\x04 \x01(\tR\tobjectKey\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"<\n" +
	"\x14GetMediaItemResponse\x12$\n" +
	"\x04item\x18\x01 \x01(\v2\x10.media.MediaItemR\x04item2\xac\x01\n" +
	"\fMediaService\x12S\n" +
	"\x10RequestUploadURL\x12\x1e.media.RequestUploadURLRequest\x1a\x1f.media.RequestUploadURLResponse\x12G\n" +
	"\fGetMediaItem\x12\x1a.media.GetMediaItemRequest\x1a\x1b.media.GetMediaItemResponseB\x1fZ\x1dwire-server/pkg/proto/mediapbb\x06proto3"

var (
	file_pkg_proto_media_proto_rawDescOnce sync.Once
	file_pkg_proto_media_proto_rawDescData []byte
)

func file_pkg_proto_media_proto_rawDescGZIP() []byte {
	file_pkg_proto_media_proto_rawDescOnce.Do(func() {
		file_pkg_proto_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_media_proto_rawDesc), len(file_pkg_proto_media_proto_rawDesc)))
	})
	return file_pkg_proto_media_proto_rawDescData
}

var file_pkg_proto_media_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_proto_media_proto_goTypes = []any{
	(*RequestUploadURLRequest)(nil),  // 0: media.RequestUploadURLRequest
	(*RequestUploadURLResponse)(nil), // 1: media.RequestUploadURLResponse
	(*GetMediaItemRequest)(nil),      // 2: media.GetMediaItemRequest
	(*MediaItem)(nil),                // 3: media.MediaItem
	(*GetMediaItemResponse)(nil),     // 4: media.GetMediaItemResponse
	nil,                              // 5: media.RequestUploadURLResponse.HeadersEntry
	(*timestamppb.Timestamp)(nil),    // 6: google.protobuf.Timestamp
}
var file_pkg_proto_media_proto_depIdxs = []int32{
	5, // 0: media.RequestUploadURLResponse.headers:type_name -> media.RequestUploadURLResponse.HeadersEntry
	6, // 1: media.RequestUploadURLResponse.expires_at:type_name -> google.protobuf.Timestamp
	6, // 2: media.MediaItem.created_at:type_name -> google.protobuf.Timestamp
	3, // 3: media.GetMediaItemResponse.item:type_name -> media.MediaItem
	0, // 4: media.MediaService.RequestUploadURL:input_type -> media.RequestUploadURLRequest
	2, // 5: media.MediaService.GetMediaItem:input_type -> media.GetMediaItemRequest
	1, // 6: media.MediaService.RequestUploadURL:output_type -> media.RequestUploadURLResponse
	4, // 7: media.MediaService.GetMediaItem:output_type -> media.GetMediaItemResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_proto_media_proto_init() }
func file_pkg_proto_media_proto_init() {
	if File_pkg_proto_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_media_proto_rawDesc), len(file_pkg_proto_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_media_proto_goTypes,
		DependencyIndexes: file_pkg_proto_media_proto_depIdxs,
		MessageInfos:      file_pkg_proto_media_proto_msgTypes,
	}.Build()
	File_pkg_proto_media_proto = out.File
	file_pkg_proto_media_proto_goTypes = nil
	file_pkg_proto_media_proto_depIdxs = nil
}
