// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: pkg/proto/call.proto

package callpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitiateCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallerId      string                 `protobuf:"bytes,1,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	CalleeIds     []string               `protobuf:"bytes,2,rep,name=callee_ids,json=calleeIds,proto3" json:"callee_ids,omitempty"`
	TraceId       string                 `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateCallRequest) Reset() {
	*x = InitiateCallRequest{}
	mi := &file_pkg_proto_call_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateCallRequest) ProtoMessage() {}

func (x *InitiateCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_call_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateCallRequest.ProtoReflect.Descriptor instead.
func (*InitiateCallRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_call_proto_rawDescGZIP(), []int{0}
}

func (x *InitiateCallRequest) GetCallerId() string {
	if x != nil {
		return x.CallerId
	}
	return ""
}

func (x *InitiateCallRequest) GetCalleeIds() []string {
	if x != nil {
		return x.CalleeIds
	}
	return nil
}

func (x *InitiateCallRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type InitiateCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateCallResponse) Reset() {
	*x = InitiateCallResponse{}
	mi := &file_pkg_proto_call_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateCallResponse) ProtoMessage() {}

func (x *InitiateCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_call_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateCallResponse.ProtoReflect.Descriptor instead.
func (*InitiateCallResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_call_proto_rawDescGZIP(), []int{1}
}

func (x *InitiateCallResponse) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *InitiateCallResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

type JoinCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	ParticipantId string                 `protobuf:"bytes,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinCallRequest) Reset() {
	*x = JoinCallRequest{}
	mi := &file_pkg_proto_call_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinCallRequest) ProtoMessage() {}

func (x *JoinCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_call_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinCallRequest.ProtoReflect.Descriptor instead.
func (*JoinCallRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_call_proto_rawDescGZIP(), []int{2}
}

func (x *JoinCallRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *JoinCallRequest) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

type JoinCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinCallResponse) Reset() {
	*x = JoinCallResponse{}
	mi := &file_pkg_proto_call_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinCallResponse) ProtoMessage() {}

func (x *JoinCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_call_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinCallResponse.ProtoReflect.Descriptor instead.
func (*JoinCallResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_call_proto_rawDescGZIP(), []int{3}
}

func (x *JoinCallResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *JoinCallResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type EndCallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	ParticipantId string                 `protobuf:"bytes,2,opt,name=participant_id,json=participantId,proto3" json:"participant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndCallRequest) Reset() {
	*x = EndCallRequest{}
	mi := &file_pkg_proto_call_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndCallRequest) ProtoMessage() {}

func (x *EndCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_call_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndCallRequest.ProtoReflect.Descriptor instead.
func (*EndCallRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_call_proto_rawDescGZIP(), []int{4}
}

func (x *EndCallRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *EndCallRequest) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

type EndCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndCallResponse) Reset() {
	*x = EndCallResponse{}
	mi := &file_pkg_proto_call_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndCallResponse) ProtoMessage() {}

func (x *EndCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_call_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndCallResponse.ProtoReflect.Descriptor instead.
func (*EndCallResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_call_proto_rawDescGZIP(), []int{5}
}

func (x *EndCallResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetTurnCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTurnCredentialsRequest) Reset() {
	*x = GetTurnCredentialsRequest{}
	mi := &file_pkg_proto_call_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTurnCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTurnCredentialsRequest) ProtoMessage() {}

func (x *GetTurnCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_call_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTurnCredentialsRequest.ProtoReflect.Descriptor instead.
func (*GetTurnCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_call_proto_rawDescGZIP(), []int{6}
}

func (x *GetTurnCredentialsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetTurnCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTurnCredentialsResponse) Reset() {
	*x = GetTurnCredentialsResponse{}
	mi := &file_pkg_proto_call_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTurnCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTurnCredentialsResponse) ProtoMessage() {}

func (x *GetTurnCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_call_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTurnCredentialsResponse.ProtoReflect.Descriptor instead.
func (*GetTurnCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_call_proto_rawDescGZIP(), []int{7}
}

func (x *GetTurnCredentialsResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetTurnCredentialsResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *GetTurnCredentialsResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

var File_pkg_proto_call_proto protoreflect.FileDescriptor

const file_pkg_proto_call_proto_rawDesc = "" +
	"\n" +
	"\x14pkg/proto/call.proto\x12\x04call\x1a\x1fgoogle/protobuf/timestamp.proto\"l\n" +
	"\x13InitiateCallRequest\x12\x1b\n" +
	"\tcaller_id\x18\x01 \x01(\tR\bcallerId\x12\x1d\n" +
	"\n" +
	"callee_ids\x18\x02 \x03(\tR\tcalleeIds\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\"j\n" +
	"\x14InitiateCallResponse\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x129\n" +
	"\n" +
	"started_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\"Q\n" +
	"\x0fJoinCallRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12%\n" +
	"\x0eparticipant_id\x18\x02 \x01(\tR\rparticipantId\"c\n" +
	"\x10JoinCallResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"P\n" +
	"\x0eEndCallRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12%\n" +
	"\x0eparticipant_id\x18\x02 \x01(\tR\rparticipantId\"+\n" +
	"\x0fEndCallResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"4\n" +
	"\x19GetTurnCredentialsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x8f\x01\n" +
	"\x1aGetTurnCredentialsResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt2\xa0\x02\n" +
	"\vCallService\x12E\n" +
	"\fInitiateCall\x12\x19.call.InitiateCallRequest\x1a\x1a.call.InitiateCallResponse\x129\n" +
	"\bJoinCall\x12\x15.call.JoinCallRequest\x1a\x16.call.JoinCallResponse\x126\n" +
	"\aEndCall\x12\x14.call.EndCallRequest\x1a\x15.call.EndCallResponse\x12W\n" +
	"\x12GetTurnCredentials\x12\x1f.call.GetTurnCredentialsRequest\x1a .call.GetTurnCredentialsResponseB\x1eZ\x1cwire-server/pkg/proto/callpbb\x06proto3"

var (
	file_pkg_proto_call_proto_rawDescOnce sync.Once
	file_pkg_proto_call_proto_rawDescData []byte
)

func file_pkg_proto_call_proto_rawDescGZIP() []byte {
	file_pkg_proto_call_proto_rawDescOnce.Do(func() {
		file_pkg_proto_call_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_call_proto_rawDesc), len(file_pkg_proto_call_proto_rawDesc)))
	})
	return file_pkg_proto_call_proto_rawDescData
}

var file_pkg_proto_call_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_proto_call_proto_goTypes = []any{
	(*InitiateCallRequest)(nil),        // 0: call.InitiateCallRequest
	(*InitiateCallResponse)(nil),       // 1: call.InitiateCallResponse
	(*JoinCallRequest)(nil),            // 2: call.JoinCallRequest
	(*JoinCallResponse)(nil),           // 3: call.JoinCallResponse
	(*EndCallRequest)(nil),             // 4: call.EndCallRequest
	(*EndCallResponse)(nil),            // 5: call.EndCallResponse
	(*GetTurnCredentialsRequest)(nil),  // 6: call.GetTurnCredentialsRequest
	(*GetTurnCredentialsResponse)(nil), // 7: call.GetTurnCredentialsResponse
	(*timestamppb.Timestamp)(nil),      // 8: google.protobuf.Timestamp
}
var file_pkg_proto_call_proto_depIdxs = []int32{
	8, // 0: call.InitiateCallResponse.started_at:type_name -> google.protobuf.Timestamp
	8, // 1: call.JoinCallResponse.expires_at:type_name -> google.protobuf.Timestamp
	8, // 2: call.GetTurnCredentialsResponse.expires_at:type_name -> google.protobuf.Timestamp
	0, // 3: call.CallService.InitiateCall:input_type -> call.InitiateCallRequest
	2, // 4: call.CallService.JoinCall:input_type -> call.JoinCallRequest
	4, // 5: call.CallService.EndCall:input_type -> call.EndCallRequest
	6, // 6: call.CallService.GetTurnCredentials:input_type -> call.GetTurnCredentialsRequest
	1, // 7: call.CallService.InitiateCall:output_type -> call.InitiateCallResponse
	3, // 8: call.CallService.JoinCall:output_type -> call.JoinCallResponse
	5, // 9: call.CallService.EndCall:output_type -> call.EndCallResponse
	7, // 10: call.CallService.GetTurnCredentials:output_type -> call.GetTurnCredentialsResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_proto_call_proto_init() }
func file_pkg_proto_call_proto_init() {
	if File_pkg_proto_call_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_call_proto_rawDesc), len(file_pkg_proto_call_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_call_proto_goTypes,
		DependencyIndexes: file_pkg_proto_call_proto_depIdxs,
		MessageInfos:      file_pkg_proto_call_proto_msgTypes,
	}.Build()
	File_pkg_proto_call_proto = out.File
	file_pkg_proto_call_proto_goTypes = nil
	file_pkg_proto_call_proto_depIdxs = nil
}
