// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/proto/ws_frames.proto

package wsframespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallSignalType int32

const (
	CallSignalType_CALL_SIGNAL_UNSPECIFIED CallSignalType = 0
	CallSignalType_CALL_SIGNAL_OFFER       CallSignalType = 1
	CallSignalType_CALL_SIGNAL_ANSWER      CallSignalType = 2
	CallSignalType_CALL_SIGNAL_CANDIDATE   CallSignalType = 3
)

// Enum value maps for CallSignalType.
var (
	CallSignalType_name = map[int32]string{
		0: "CALL_SIGNAL_UNSPECIFIED",
		1: "CALL_SIGNAL_OFFER",
		2: "CALL_SIGNAL_ANSWER",
		3: "CALL_SIGNAL_CANDIDATE",
	}
	CallSignalType_value = map[string]int32{
		"CALL_SIGNAL_UNSPECIFIED": 0,
		"CALL_SIGNAL_OFFER":       1,
		"CALL_SIGNAL_ANSWER":      2,
		"CALL_SIGNAL_CANDIDATE":   3,
	}
)

func (x CallSignalType) Enum() *CallSignalType {
	p := new(CallSignalType)
	*p = x
	return p
}

func (x CallSignalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallSignalType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_ws_frames_proto_enumTypes[0].Descriptor()
}

func (CallSignalType) Type() protoreflect.EnumType {
	return &file_pkg_proto_ws_frames_proto_enumTypes[0]
}

func (x CallSignalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallSignalType.Descriptor instead.
func (CallSignalType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_ws_frames_proto_rawDescGZIP(), []int{0}
}

type ChatMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MessageId       string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderPhone     string                 `protobuf:"bytes,2,opt,name=sender_phone,json=senderPhone,proto3" json:"sender_phone,omitempty"`
	RecipientPhones []string               `protobuf:"bytes,3,rep,name=recipient_phones,json=recipientPhones,proto3" json:"recipient_phones,omitempty"`
	ConversationId  string                 `protobuf:"bytes,4,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // This stays as is, but will be derived from phones
	Body            string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	TraceId         string                 `protobuf:"bytes,6,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	GroupMessage    bool                   `protobuf:"varint,8,opt,name=group_message,json=groupMessage,proto3" json:"group_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_pkg_proto_ws_frames_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ws_frames_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ws_frames_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ChatMessage) GetSenderPhone() string {
	if x != nil {
		return x.SenderPhone
	}
	return ""
}

func (x *ChatMessage) GetRecipientPhones() []string {
	if x != nil {
		return x.RecipientPhones
	}
	return nil
}

func (x *ChatMessage) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ChatMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *ChatMessage) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ChatMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ChatMessage) GetGroupMessage() bool {
	if x != nil {
		return x.GroupMessage
	}
	return false
}

type Frame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	TraceId       string                 `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	UserPhone     string                 `protobuf:"bytes,4,opt,name=user_phone,json=userPhone,proto3" json:"user_phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_pkg_proto_ws_frames_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ws_frames_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ws_frames_proto_rawDescGZIP(), []int{1}
}

func (x *Frame) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Frame) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Frame) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Frame) GetUserPhone() string {
	if x != nil {
		return x.UserPhone
	}
	return ""
}

type Outbound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Targets       []string               `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"` // These are now phones
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Outbound) Reset() {
	*x = Outbound{}
	mi := &file_pkg_proto_ws_frames_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outbound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outbound) ProtoMessage() {}

func (x *Outbound) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ws_frames_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outbound.ProtoReflect.Descriptor instead.
func (*Outbound) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ws_frames_proto_rawDescGZIP(), []int{2}
}

func (x *Outbound) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *Outbound) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	TraceId       string                 `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_pkg_proto_ws_frames_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ws_frames_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ws_frames_proto_rawDescGZIP(), []int{3}
}

func (x *Ack) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Ack) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Ack) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type PresenceUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserPhone     string                 `protobuf:"bytes,1,opt,name=user_phone,json=userPhone,proto3" json:"user_phone,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceUpdate) Reset() {
	*x = PresenceUpdate{}
	mi := &file_pkg_proto_ws_frames_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceUpdate) ProtoMessage() {}

func (x *PresenceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ws_frames_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceUpdate.ProtoReflect.Descriptor instead.
func (*PresenceUpdate) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ws_frames_proto_rawDescGZIP(), []int{4}
}

func (x *PresenceUpdate) GetUserPhone() string {
	if x != nil {
		return x.UserPhone
	}
	return ""
}

func (x *PresenceUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PresenceUpdate) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

type CallSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Type          CallSignalType         `protobuf:"varint,2,opt,name=type,proto3,enum=wsframes.CallSignalType" json:"type,omitempty"`
	FromUserPhone string                 `protobuf:"bytes,3,opt,name=from_user_phone,json=fromUserPhone,proto3" json:"from_user_phone,omitempty"`
	ToUserPhone   string                 `protobuf:"bytes,4,opt,name=to_user_phone,json=toUserPhone,proto3" json:"to_user_phone,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	TraceId       string                 `protobuf:"bytes,6,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallSignal) Reset() {
	*x = CallSignal{}
	mi := &file_pkg_proto_ws_frames_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallSignal) ProtoMessage() {}

func (x *CallSignal) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ws_frames_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallSignal.ProtoReflect.Descriptor instead.
func (*CallSignal) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ws_frames_proto_rawDescGZIP(), []int{5}
}

func (x *CallSignal) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *CallSignal) GetType() CallSignalType {
	if x != nil {
		return x.Type
	}
	return CallSignalType_CALL_SIGNAL_UNSPECIFIED
}

func (x *CallSignal) GetFromUserPhone() string {
	if x != nil {
		return x.FromUserPhone
	}
	return ""
}

func (x *CallSignal) GetToUserPhone() string {
	if x != nil {
		return x.ToUserPhone
	}
	return ""
}

func (x *CallSignal) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CallSignal) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type Typing struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserPhone      string                 `protobuf:"bytes,1,opt,name=user_phone,json=userPhone,proto3" json:"user_phone,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Typing         bool                   `protobuf:"varint,3,opt,name=typing,proto3" json:"typing,omitempty"`
	TraceId        string                 `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Typing) Reset() {
	*x = Typing{}
	mi := &file_pkg_proto_ws_frames_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Typing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Typing) ProtoMessage() {}

func (x *Typing) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ws_frames_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Typing.ProtoReflect.Descriptor instead.
func (*Typing) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ws_frames_proto_rawDescGZIP(), []int{6}
}

func (x *Typing) GetUserPhone() string {
	if x != nil {
		return x.UserPhone
	}
	return ""
}

func (x *Typing) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *Typing) GetTyping() bool {
	if x != nil {
		return x.Typing
	}
	return false
}

func (x *Typing) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

var File_pkg_proto_ws_frames_proto protoreflect.FileDescriptor

const file_pkg_proto_ws_frames_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/proto/ws_frames.proto\x12\bwsframes\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb2\x02\n" +
	"\vChatMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12!\n" +
	"\fsender_phone\x18\x02 \x01(\tR\vsenderPhone\x12)\n" +
	"\x10recipient_phones\x18\x03 \x03(\tR\x0frecipientPhones\x12'\n" +
	"\x0fconversation_id\x18\x04 \x01(\tR\x0econversationId\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x12\x19\n" +
	"\btrace_id\x18\x06 \x01(\tR\atraceId\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12#\n" +
	"\rgroup_message\x18\b \x01(\bR\fgroupMessage\"o\n" +
	"\x05Frame\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"user_phone\x18\x04 \x01(\tR\tuserPhone\"8\n" +
	"\bOutbound\x12\x18\n" +
	"\atargets\x18\x01 \x03(\tR\atargets\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"W\n" +
	"\x03Ack\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\"\x80\x01\n" +
	"\x0ePresenceUpdate\x12\x1d\n" +
	"\n" +
	"user_phone\x18\x01 \x01(\tR\tuserPhone\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x127\n" +
	"\tlast_seen\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\"\xd4\x01\n" +
	"\n" +
	"CallSignal\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x18.wsframes.CallSignalTypeR\x04type\x12&\n" +
	"\x0ffrom_user_phone\x18\x03 \x01(\tR\rfromUserPhone\x12\"\n" +
	"\rto_user_phone\x18\x04 \x01(\tR\vtoUserPhone\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12\x19\n" +
	"\btrace_id\x18\x06 \x01(\tR\atraceId\"\x83\x01\n" +
	"\x06Typing\x12\x1d\n" +
	"\n" +
	"user_phone\x18\x01 \x01(\tR\tuserPhone\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x16\n" +
	"\x06typing\x18\x03 \x01(\bR\x06typing\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\tR\atraceId*w\n" +
	"\x0eCallSignalType\x12\x1b\n" +
	"\x17CALL_SIGNAL_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11CALL_SIGNAL_OFFER\x10\x01\x12\x16\n" +
	"\x12CALL_SIGNAL_ANSWER\x10\x02\x12\x19\n" +
	"\x15CALL_SIGNAL_CANDIDATE\x10\x03B\"Z wire-server/pkg/proto/wsframespbb\x06proto3"

var (
	file_pkg_proto_ws_frames_proto_rawDescOnce sync.Once
	file_pkg_proto_ws_frames_proto_rawDescData []byte
)

func file_pkg_proto_ws_frames_proto_rawDescGZIP() []byte {
	file_pkg_proto_ws_frames_proto_rawDescOnce.Do(func() {
		file_pkg_proto_ws_frames_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_ws_frames_proto_rawDesc), len(file_pkg_proto_ws_frames_proto_rawDesc)))
	})
	return file_pkg_proto_ws_frames_proto_rawDescData
}

var file_pkg_proto_ws_frames_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_ws_frames_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_proto_ws_frames_proto_goTypes = []any{
	(CallSignalType)(0),           // 0: wsframes.CallSignalType
	(*ChatMessage)(nil),           // 1: wsframes.ChatMessage
	(*Frame)(nil),                 // 2: wsframes.Frame
	(*Outbound)(nil),              // 3: wsframes.Outbound
	(*Ack)(nil),                   // 4: wsframes.Ack
	(*PresenceUpdate)(nil),        // 5: wsframes.PresenceUpdate
	(*CallSignal)(nil),            // 6: wsframes.CallSignal
	(*Typing)(nil),                // 7: wsframes.Typing
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_pkg_proto_ws_frames_proto_depIdxs = []int32{
	8, // 0: wsframes.ChatMessage.created_at:type_name -> google.protobuf.Timestamp
	8, // 1: wsframes.PresenceUpdate.last_seen:type_name -> google.protobuf.Timestamp
	0, // 2: wsframes.CallSignal.type:type_name -> wsframes.CallSignalType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_proto_ws_frames_proto_init() }
func file_pkg_proto_ws_frames_proto_init() {
	if File_pkg_proto_ws_frames_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_ws_frames_proto_rawDesc), len(file_pkg_proto_ws_frames_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_ws_frames_proto_goTypes,
		DependencyIndexes: file_pkg_proto_ws_frames_proto_depIdxs,
		EnumInfos:         file_pkg_proto_ws_frames_proto_enumTypes,
		MessageInfos:      file_pkg_proto_ws_frames_proto_msgTypes,
	}.Build()
	File_pkg_proto_ws_frames_proto = out.File
	file_pkg_proto_ws_frames_proto_goTypes = nil
	file_pkg_proto_ws_frames_proto_depIdxs = nil
}
